project:
  type: website 
  output-dir: docs

website:
  title: "personal-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cv.pdf
        text: "CV"
      - href: "bio.pdf"
        text: "Bio"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

